# Generated by Django 5.1.6 on 2025-02-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genero',
            new_name='genre',
        ),
    ]
